# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Tronic"
license = "MIT"
licenselink = "https://github.com/jacobhands/tronic/blob/master/LICENSE.md"
description = "Hugo theme based on Josh Shermon's blog at joshtronic.com"
homepage = "https://github.com/jacobhands/tronic"
tags = ["blog", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Jacob Hands"
  homepage = "http://jacobhands.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
