baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "../../../tronic"

[permalinks]
	post = "/:year/:month/:slug"

[params]
    description = "Description of my blog. You would say some things about yourself here!"
